### PR TITLE
added alarm status to updates for SHM

### PR DESCRIPTION
**Pull request by pstuart**
this is the proper file folder structure for github integration with ST.

### CODE REVIEW

**Comment by jshimko** [comment]
So does this mean that a new file is going to need to be added every time the version changes in the ST IDE?  That seems a little nuts when you can just use a Github tag.  That's literally what tags are for (to reference code at a point in time, like a version).

**Comment by pstuart** [comment]
Not sure what you mean.  I have a variable in the smartapp to sync versioning.  The github integration with the IDE allows for pulling down latest code from repo.  This was a manual PR because the commit in the IDE was blocked.  Which is a good thing.

**Comment by pstuart** [comment]
I think this commit now creates the proper structure and removes versioning from smartapp

**Comment by pstuart** [comment]
Latest updates, with endpoint documentation and json returns

**Review by jshimko — APPROVED** [review]
Great stuff!

**Pull request merged**
